### ISSUE TITLE
maven 설치 가이드 

### ISSUE THREAD

**Issue by leejiyoun88** [bekay-perf/SUT#1]
mvn 설치 방법
https://www.unixmen.com/install-apache-ant-maven-tomcat-centos-76-5/
가이드 참조 

./mvnw clean package 명령은 
System-Under-Test 경로에서 실행하면 되고, 파일 권한 'chmod 777 mvnw' 변경해서 실행해 줬습니다.

**Comment by bekay-perf** [comment]
대문 가이드 문서에  반영완료
